server:
  port: 5555
spring:
  mail:
    username: javamail_lin@163.com
    password: 
    host: 
  application:
    name: Linms-Blog
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
      username: root
      password: 521020
      url: jdbc:mysql://localhost:3306/linms?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1

rabbitmq:
  exchange:
    mail-exchange: "exchange"
  queue:
    mail-queue: "mail-queue"
